name: PR Checks
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test:unit
    - name: Checks
      run: node checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}