name: PR Checks
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Install and build
      run: |
        npm install
        npm run build:all
    - name: Run status checks
      run: node checks
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}